
type WeatherCondition = {
  [x:string]: {
    day: string;
    night: string;
  }
}

export const weatherModifiers: string[] = ['a', 'and', 'conditions', 'chance', 'exist', 'few', 'freezing', 'heavy', 'in', 'light', 'like', 'mostly', 'of', 'partial', 'partly', 'patches', 'patchy', 'presently', 'then', 'vicinity', 'warning', 'watch', 'with']

export const weatherConditions: WeatherCondition = {
  'sunny': { day: 'day-sunny', night: 'night-clear' },
  'fair': { day: 'day-sunny', night: 'night-clear' },
  'clear': { day: 'day-sunny', night: 'night-clear' },
  'fair with haze': { day: 'day-sunny', night: 'night-clear' },
  'clear with haze': { day: 'day-sunny', night: 'night-clear' },
  'fair and breezy': { day: 'day-sunny', night: 'night-clear' },
  'clear and breezy': { day: 'day-sunny', night: 'night-clear' },

  // 'mostly sunny': { day: 'day-cloudy-high', night: 'night-alt-cloudy-high' },
  'a few clouds': { day: 'day-cloudy-high', night: 'night-alt-cloudy-high' },
  'a few clouds with haze': { day: 'day-cloudy-high', night: 'night-alt-cloudy-high' },
  'a few clouds and breezy': { day: 'day-cloudy-high', night: 'night-alt-cloudy-high' },

  'partly sunny': { day: 'day-cloudy', night: 'night-alt-partly-cloudy' },
  'partly cloudy': { day: 'day-cloudy', night: 'night-alt-partly-cloudy' },
  'partly cloudy with haze': { day: 'day-cloudy', night: 'night-alt-partly-cloudy' },
  'partly cloudy and breezy': { day: 'day-cloudy', night: 'night-alt-partly-cloudy' },
  'patchy fog then mostly sunny': { day: 'day-cloudy', night: 'night-alt-partly-cloudy' },

  'mostly cloudy': { day: 'day-cloudy', night: 'night-alt-cloudy' },
  'mostly cloudy with haze': { day: 'day-cloudy', night: 'night-alt-cloudy' },
  'mostly cloudy and breezy': { day: 'day-cloudy', night: 'night-alt-cloudy' },
  'patchy fog then partly sunny': { day: 'day-cloudy', night: 'night-alt-cloudy' },

  'cloudy': { day: 'cloudy', night: 'cloudy' },
  'overcast': { day: 'cloudy', night: 'cloudy' },
  'overcast with haze': { day: 'cloudy', night: 'cloudy' },
  'overcast and breezy': { day: 'cloudy', night: 'cloudy' },

  'snow': { day: 'snow', night: 'snow' },
  'light snow': { day: 'snow', night: 'snow' },
  'heavy snow': { day: 'snow', night: 'snow' },
  'snow showers': { day: 'snow', night: 'snow' },
  'light snow showers': { day: 'snow', night: 'snow' },
  'heavy snow showers': { day: 'snow', night: 'snow' },
  'showers snow': { day: 'snow', night: 'snow' },
  'light showers snow': { day: 'snow', night: 'snow' },
  'heavy showers snow': { day: 'snow', night: 'snow' },
  'snow fog/mist': { day: 'snow', night: 'snow' },
  'light snow fog/mist': { day: 'snow', night: 'snow' },
  'heavy snow fog/mist': { day: 'snow', night: 'snow' },
  'snow showers fog/mist': { day: 'snow', night: 'snow' },
  'light snow showers fog/mist': { day: 'snow', night: 'snow' },
  'heavy snow showers fog/mist': { day: 'snow', night: 'snow' },
  'showers snow fog/mist': { day: 'snow', night: 'snow' },
  'light showers snow fog/mist': { day: 'snow', night: 'snow' },
  'heavy showers snow fog/mist': { day: 'snow', night: 'snow' },
  'snow fog': { day: 'snow', night: 'snow' },
  'light snow fog': { day: 'snow', night: 'snow' },
  'heavy snow fog': { day: 'snow', night: 'snow' },
  'snow showers fog': { day: 'snow', night: 'snow' },
  'light snow showers fog': { day: 'snow', night: 'snow' },
  'heavy snow showers fog': { day: 'snow', night: 'snow' },
  'showers in vicinity snow': { day: 'snow', night: 'snow' },
  'snow showers in vicinity': { day: 'snow', night: 'snow' },
  'snow showers in vicinity fog/mist': { day: 'snow', night: 'snow' },
  'snow showers in vicinity fog': { day: 'snow', night: 'snow' },
  'low drifting snow': { day: 'snow', night: 'snow' },
  'blowing snow': { day: 'snow', night: 'snow' },
  'snow low drifting snow': { day: 'snow', night: 'snow' },
  'snow blowing snow': { day: 'snow', night: 'snow' },
  'light snow low drifting snow': { day: 'snow', night: 'snow' },
  'light snow blowing snow': { day: 'snow', night: 'snow' },
  'light snow blowing snow fog/mist': { day: 'snow', night: 'snow' },
  'heavy snow low drifting snow': { day: 'snow', night: 'snow' },
  'heavy snow blowing snow': { day: 'snow', night: 'snow' },
  'thunderstorm snow': { day: 'snow', night: 'snow' },
  'light thunderstorm snow': { day: 'snow', night: 'snow' },
  'heavy thunderstorm snow': { day: 'snow', night: 'snow' },
  'snow grains': { day: 'snow', night: 'snow' },
  'light snow grains': { day: 'snow', night: 'snow' },
  'heavy snow grains': { day: 'snow', night: 'snow' },
  'heavy blowing snow': { day: 'snow', night: 'snow' },
  'blowing snow in vicinity': { day: 'snow', night: 'snow' },

  'rain snow': { day: 'sleet', night: 'sleet' },
  'light rain snow': { day: 'sleet', night: 'sleet' },
  'heavy rain snow': { day: 'sleet', night: 'sleet' },
  'snow rain': { day: 'sleet', night: 'sleet' },
  'light snow rain': { day: 'sleet', night: 'sleet' },
  'heavy snow rain': { day: 'sleet', night: 'sleet' },
  'drizzle snow': { day: 'sleet', night: 'sleet' },
  'light drizzle snow': { day: 'sleet', night: 'sleet' },
  'heavy drizzle snow': { day: 'sleet', night: 'sleet' },
  'snow drizzle': { day: 'sleet', night: 'sleet' },
  'light snow drizzle': { day: 'sleet', night: 'sleet' },

  'rain ice pellets': { day: 'sleet', night: 'sleet' },
  'light rain ice pellets': { day: 'sleet', night: 'sleet' },
  'heavy rain ice pellets': { day: 'sleet', night: 'sleet' },
  'drizzle ice pellets': { day: 'sleet', night: 'sleet' },
  'light drizzle ice pellets': { day: 'sleet', night: 'sleet' },
  'heavy drizzle ice pellets': { day: 'sleet', night: 'sleet' },
  'ice pellets rain': { day: 'sleet', night: 'sleet' },
  'light ice pellets rain': { day: 'sleet', night: 'sleet' },
  'heavy ice pellets rain': { day: 'sleet', night: 'sleet' },
  'ice pellets drizzle': { day: 'sleet', night: 'sleet' },
  'light ice pellets drizzle': { day: 'sleet', night: 'sleet' },
  'heavy ice pellets drizzle': { day: 'sleet', night: 'sleet' },

  'freezing rain': { day: 'rain-wind', night: 'rain-wind' },
  'freezing drizzle': { day: 'rain-wind', night: 'rain-wind' },
  'light freezing rain': { day: 'rain-wind', night: 'rain-wind' },
  'light freezing drizzle': { day: 'rain-wind', night: 'rain-wind' },
  'heavy freezing rain': { day: 'rain-wind', night: 'rain-wind' },
  'heavy freezing drizzle': { day: 'rain-wind', night: 'rain-wind' },
  'freezing rain in vicinity': { day: 'rain-wind', night: 'rain-wind' },
  'freezing drizzle in vicinity': { day: 'rain-wind', night: 'rain-wind' },

  'freezing rain rain': { day: 'rain-wind', night: 'rain-wind' },
  'light freezing rain rain': { day: 'rain-wind', night: 'rain-wind' },
  'heavy freezing rain rain': { day: 'rain-wind', night: 'rain-wind' },
  'rain freezing rain': { day: 'rain-wind', night: 'rain-wind' },
  'light rain freezing rain': { day: 'rain-wind', night: 'rain-wind' },
  'heavy rain freezing rain': { day: 'rain-wind', night: 'rain-wind' },
  'freezing drizzle rain': { day: 'rain-wind', night: 'rain-wind' },
  'light freezing drizzle rain': { day: 'rain-wind', night: 'rain-wind' },
  'heavy freezing drizzle rain': { day: 'rain-wind', night: 'rain-wind' },
  'rain freezing drizzle': { day: 'rain-wind', night: 'rain-wind' },
  'light rain freezing drizzle': { day: 'rain-wind', night: 'rain-wind' },
  'heavy rain freezing drizzle': { day: 'rain-wind', night: 'rain-wind' },

  'freezing rain snow': { day: 'snow-wind', night: 'snow-wind' },
  'light freezing rain snow': { day: 'snow-wind', night: 'snow-wind' },
  'heavy freezing rain snow': { day: 'snow-wind', night: 'snow-wind' },
  'freezing drizzle snow': { day: 'snow-wind', night: 'snow-wind' },
  'light freezing drizzle snow': { day: 'snow-wind', night: 'snow-wind' },
  'heavy freezing drizzle snow': { day: 'snow-wind', night: 'snow-wind' },
  'snow freezing rain': { day: 'snow-wind', night: 'snow-wind' },
  'light snow freezing rain': { day: 'snow-wind', night: 'snow-wind' },
  'heavy snow freezing rain': { day: 'snow-wind', night: 'snow-wind' },
  'snow freezing drizzle': { day: 'snow-wind', night: 'snow-wind' },
  'light snow freezing drizzle': { day: 'snow-wind', night: 'snow-wind' },
  'heavy snow freezing drizzle': { day: 'snow-wind', night: 'snow-wind' },

  'ice pellets': { day: 'hail', night: 'hail' },
  'light ice pellets': { day: 'hail', night: 'hail' },
  'heavy ice pellets': { day: 'hail', night: 'hail' },
  'ice pellets in vicinity': { day: 'hail', night: 'hail' },
  'showers ice pellets': { day: 'hail', night: 'hail' },
  'thunderstorm ice pellets': { day: 'hail', night: 'hail' },
  'ice crystals': { day: 'hail', night: 'hail' },
  'hail': { day: 'hail', night: 'hail' },
  'small hail/snow pellets': { day: 'hail', night: 'hail' },
  'light small hail/snow pellets': { day: 'hail', night: 'hail' },
  'heavy small hail/snow pellets': { day: 'hail', night: 'hail' },
  'showers hail': { day: 'hail', night: 'hail' },
  'hail showers': { day: 'hail', night: 'hail' },

  'snow ice pellets': { day: 'hail', night: 'hail' },

  'light rain': { day: 'day-rain-mix', night: 'night-rain-mix' },
  'drizzle': { day: 'day-rain-mix', night: 'night-rain-mix' },
  'light drizzle': { day: 'day-rain-mix', night: 'night-rain-mix' },
  'heavy drizzle': { day: 'day-rain-mix', night: 'night-rain-mix' },
  'light rain fog/mist': { day: 'day-rain-mix', night: 'night-rain-mix' },
  'drizzle fog/mist': { day: 'day-rain-mix', night: 'night-rain-mix' },
  'light drizzle fog/mist': { day: 'day-rain-mix', night: 'night-rain-mix' },
  'heavy drizzle fog/mist': { day: 'day-rain-mix', night: 'night-rain-mix' },
  'light rain fog': { day: 'day-rain-mix', night: 'night-rain-mix' },
  'drizzle fog': { day: 'day-rain-mix', night: 'night-rain-mix' },
  'light drizzle fog': { day: 'day-rain-mix', night: 'night-rain-mix' },
  'heavy drizzle fog': { day: 'day-rain-mix', night: 'night-rain-mix' },

  'rain': { day: 'day-rain', night: 'night-alt-rain' },
  'heavy rain': { day: 'day-rain', night: 'night-alt-rain' },
  'rain fog/mist': { day: 'day-rain', night: 'night-alt-rain' },
  'heavy rain fog/mist': { day: 'day-rain', night: 'night-alt-rain' },
  'rain fog': { day: 'day-rain', night: 'night-alt-rain' },
  'heavy rain fog': { day: 'day-rain', night: 'night-alt-rain' },

  'showers': { day: 'day-showers', night: 'night-alt-showers' },
  'rain showers': { day: 'day-showers', night: 'night-alt-showers' },
  'light rain showers': { day: 'day-showers', night: 'night-alt-showers' },
  'light rain and breezy': { day: 'day-showers', night: 'night-alt-showers' },
  'heavy rain showers': { day: 'day-showers', night: 'night-alt-showers' },
  'rain showers in vicinity': { day: 'day-showers', night: 'night-alt-showers' },
  'light showers rain': { day: 'day-showers', night: 'night-alt-showers' },
  'heavy showers rain': { day: 'day-showers', night: 'night-alt-showers' },
  'showers rain': { day: 'day-showers', night: 'night-alt-showers' },
  'showers rain in vicinity': { day: 'day-showers', night: 'night-alt-showers' },
  'rain showers fog/mist': { day: 'day-showers', night: 'night-alt-showers' },
  'light rain showers fog/mist': { day: 'day-showers', night: 'night-alt-showers' },
  'heavy rain showers fog/mist': { day: 'day-showers', night: 'night-alt-showers' },
  'rain showers in vicinity fog/mist': { day: 'day-showers', night: 'night-alt-showers' },
  'light showers rain fog/mist': { day: 'day-showers', night: 'night-alt-showers' },
  'heavy showers rain fog/mist': { day: 'day-showers', night: 'night-alt-showers' },
  'showers rain fog/mist': { day: 'day-showers', night: 'night-alt-showers' },
  'showers rain in vicinity fog/mist': { day: 'day-showers', night: 'night-alt-showers' },

  'showers in vicinity': { day: 'day-showers', night: 'night-alt-showers' },
  'showers in vicinity fog/mist': { day: 'day-showers', night: 'night-alt-showers' },
  'showers in vicinity fog': { day: 'day-showers', night: 'night-alt-showers' },
  'showers in vicinity haze': { day: 'day-showers', night: 'night-alt-showers' },

  'thunderstorm': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm rain': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'light thunderstorm rain': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'heavy thunderstorm rain': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm rain fog/mist': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'light thunderstorm rain fog/mist': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'heavy thunderstorm rain fog and windy': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'heavy thunderstorm rain fog/mist': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm showers in vicinity': { day: 'storm-showers', night: 'storm-showers' },
  'light thunderstorm rain haze': { day: 'storm-showers', night: 'storm-showers' },
  'heavy thunderstorm rain haze': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm fog': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'light thunderstorm rain fog': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'heavy thunderstorm rain fog': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm light rain': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm heavy rain': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm light rain fog/mist': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm heavy rain fog/mist': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm in vicinity fog/mist': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm in vicinity haze': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm haze in vicinity': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm light rain haze': { day: 'storm-showers', night: 'storm-showers' },
  'thunderstorm heavy rain haze': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm light rain fog': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm heavy rain fog': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm hail': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'light thunderstorm rain hail': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'heavy thunderstorm rain hail': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm rain hail fog/mist': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'light thunderstorm rain hail fog/mist': { day: 'storm-showers', night: 'storm-showers' },
  'heavy thunderstorm rain hail fog/hail': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm showers in vicinity hail': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'light thunderstorm rain hail haze': { day: 'storm-showers', night: 'storm-showers' },
  'heavy thunderstorm rain hail haze': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm hail fog': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'light thunderstorm rain hail fog': { day: 'storm-showers', night: 'storm-showers' },
  'heavy thunderstorm rain hail fog': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm light rain hail': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm heavy rain hail': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm light rain hail fog/mist': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm heavy rain hail fog/mist': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm in vicinity hail': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm in vicinity hail haze': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm haze in vicinity hail': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm light rain hail haze': { day: 'storm-showers', night: 'storm-showers' },
  'thunderstorm heavy rain hail haze': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm light rain hail fog': { day: 'storm-showers', night: 'storm-showers' },
  'thunderstorm heavy rain hail fog': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm small hail/snow pellets': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm rain small hail/snow pellets': { day: 'storm-showers', night: 'storm-showers' },
  'light thunderstorm rain small hail/snow pellets': { day: 'storm-showers', night: 'storm-showers' },
  'heavy thunderstorm rain small hail/snow pellets': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'showers and thunderstorms likely': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'showers and thunderstorms': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },

  'thunderstorm in vicinity': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },
  'thunderstorm in vicinity fog': { day: 'day-thunderstorm', night: 'night-alt-thunderstorm' },

  'funnel cloud': { day: 'tornado', night: 'tornado' },
  'funnel cloud in vicinity': { day: 'tornado', night: 'tornado' },
  'tornado/water spout': { day: 'tornado', night: 'tornado' },

  'tornado': { day: 'tornado', night: 'tornado' },

  'hurricane': { day: 'hurricane', night: 'hurricane' },

  'hurricane warning': { day: 'hurricane-warning', night: 'hurricane-warning' },

  'hurricane watch': { day: 'hurricane-warning', night: 'hurricane-warning' },

  'tropical storm warning': { day: 'storm-warning', night: 'storm-warning' },

  'tropical storm watch': { day: 'storm-warning', night: 'storm-warning' },

  'tropical storm conditions presently exist w/hurricane warning in effect': { day: 'gale-warning', night: 'gale-warning' },

  'windy': { day: 'windy', night: 'windy' },
  'breezy': { day: 'windy', night: 'windy' },
  'fair and windy': { day: 'windy', night: 'windy' },

  'a few clouds and windy': { day: 'cloudy-windy', night: 'cloudy-windy' },

  'partly cloudy and windy': { day: 'cloudy-windy', night: 'cloudy-windy' },

  'mostly cloudy and windy': { day: 'cloudy-windy', night: 'cloudy-windy' },

  'overcast and windy': { day: 'cloudy-windy', night: 'cloudy-windy' },

  'dust': { day: 'dust', night: 'dust' },
  'dusty': { day: 'dust', night: 'dust' },
  'low drifting dust': { day: 'dust', night: 'dust' },
  'blowing dust': { day: 'sandstorm', night: 'sandstorm' },
  'sand': { day: 'sandstorm', night: 'sandstorm' },
  'blowing sand': { day: 'sandstorm', night: 'sandstorm' },
  'low drifting sand': { day: 'sandstorm', night: 'sandstorm' },
  'dust/sand whirls': { day: 'sandstorm', night: 'sandstorm' },
  'dust/sand whirls in vicinity': { day: 'sandstorm', night: 'sandstorm' },
  'dust storm': { day: 'sandstorm', night: 'sandstorm' },
  'heavy dust storm': { day: 'sandstorm', night: 'sandstorm' },
  'dust storm in vicinity': { day: 'sandstorm', night: 'sandstorm' },
  'sand storm': { day: 'sandstorm', night: 'sandstorm' },
  'sandstorm': { day: 'sandstorm', night: 'sandstorm' },
  'heavy sand storm': { day: 'sandstorm', night: 'sandstorm' },
  'sand storm in vicinity': { day: 'sandstorm', night: 'sandstorm' },

  'smoke': { day: 'smoke', night: 'smoke' },
  'smokey': { day: 'smoke', night: 'smoke' },

  'haze': { day: 'day-haze', night: 'smog' },
  'hazy': { day: 'day-haze', night: 'smog' },

  'hot': { day: 'thermometer', night: 'thermometer' },

  'cold': { day: 'snowflake-cold', night: 'snowflake-cold' },
  'freezing': { day: 'snowflake-cold', night: 'snowflake-cold' },

  'blizzard': { day: 'snow-wind', night: 'snow-wind' },

  'fog': { day: 'fog', night: 'fog' },
  'foggy': { day: 'fog', night: 'fog' },
  'fog/mist': { day: 'fog', night: 'fog' },
  'freezing fog': { day: 'fog', night: 'fog' },
  'shallow fog': { day: 'fog', night: 'fog' },
  'partial fog': { day: 'fog', night: 'fog' },
  'patches of fog': { day: 'fog', night: 'fog' },
  'fog in vicinity': { day: 'fog', night: 'fog' },
  'freezing fog in vicinity': { day: 'fog', night: 'fog' },
  'shallow fog in vicinity': { day: 'fog', night: 'fog' },
  'partial fog in vicinity': { day: 'fog', night: 'fog' },
  'patches of fog in vicinity': { day: 'fog', night: 'fog' },
  'light freezing fog': { day: 'fog', night: 'fog' },
  'heavy freezing fog': { day: 'fog', night: 'fog' },
}
