import { ProgressReportWaffleOverviewChip } from "./index"

type Props = {
  id: string;
}

const breakdowns = [
	{ id: '0', sc: '1', episode: '1', isComplete: true },
	{ id: '1', sc: '2', episode: '1', isComplete: false },
	{ id: '2', sc: '3', episode: '1', isComplete: true },
	{ id: '3', sc: '4', episode: '1', isComplete: false },
	{ id: '4', sc: '5', episode: '1', isComplete: false },
	{ id: '5', sc: '6', episode: '1', isComplete: true },
	{ id: '6', sc: '7', episode: '1', isComplete: false },
	{ id: '7', sc: '8', episode: '1', isComplete: true },
	{ id: '8', sc: '9', episode: '1', isComplete: false },
	{ id: '9', sc: '10', episode: '1', isComplete: true },
	{ id: '10', sc: '11', episode: '1', isComplete: false },
	{ id: '11', sc: '12', episode: '1', isComplete: false },
	{ id: '12', sc: '13', episode: '1', isComplete: false },
	{ id: '13', sc: '14', episode: '1', isComplete: false },
	{ id: '14', sc: '15', episode: '1', isComplete: false },
	{ id: '15', sc: '16', episode: '1', isComplete: true },
	{ id: '16', sc: '17', episode: '1', isComplete: false },
	{ id: '17', sc: '18', episode: '1', isComplete: false },
	{ id: '18', sc: '19', episode: '1', isComplete: true },
	{ id: '19', sc: '20', episode: '1', isComplete: false },
	{ id: '20', sc: '21', episode: '1', isComplete: false },
	{ id: '21', sc: '22', episode: '1', isComplete: false },
	{ id: '22', sc: '23', episode: '1', isComplete: false },
	{ id: '23', sc: '24', episode: '1', isComplete: false },
	{ id: '24', sc: '25', episode: '1', isComplete: true },
	{ id: '25', sc: '26', episode: '1', isComplete: false },
	{ id: '26', sc: '27', episode: '1', isComplete: false },
	{ id: '27', sc: '28', episode: '1', isComplete: true },
	{ id: '28', sc: '29', episode: '1', isComplete: true },
	{ id: '29', sc: '30', episode: '1', isComplete: true },
	{ id: '30', sc: '31', episode: '1', isComplete: true },
	{ id: '31', sc: '32', episode: '1', isComplete: true },
	{ id: '32', sc: '33', episode: '1', isComplete: false },
	{ id: '33', sc: '34', episode: '1', isComplete: false },
	{ id: '34', sc: '35', episode: '1', isComplete: true },
	{ id: '35', sc: '36', episode: '1', isComplete: true },
	{ id: '36', sc: '37', episode: '1', isComplete: false },
	{ id: '37', sc: '38', episode: '1', isComplete: true },
	{ id: '38', sc: '39', episode: '1', isComplete: true },
	{ id: '39', sc: '40', episode: '1', isComplete: false },
	{ id: '40', sc: '41', episode: '1', isComplete: true },
	{ id: '41', sc: '42', episode: '1', isComplete: true },
	{ id: '42', sc: '43', episode: '1', isComplete: true },
	{ id: '43', sc: '44', episode: '1', isComplete: false },
	{ id: '44', sc: '45', episode: '1', isComplete: true },
	{ id: '45', sc: '46', episode: '1', isComplete: false },
	{ id: '46', sc: '47', episode: '1', isComplete: false },
	{ id: '47', sc: '48', episode: '1', isComplete: true },
	{ id: '48', sc: '49', episode: '1', isComplete: true },
	{ id: '49', sc: '50', episode: '1', isComplete: false },
	{ id: '50', sc: '51', episode: '1', isComplete: false },
	{ id: '51', sc: '52', episode: '1', isComplete: false },
	{ id: '52', sc: '53', episode: '1', isComplete: false },
	{ id: '53', sc: '54', episode: '1', isComplete: false },
	{ id: '54', sc: '55', episode: '1', isComplete: true },
	{ id: '55', sc: '56', episode: '1', isComplete: true },
	{ id: '56', sc: '57', episode: '1', isComplete: false },
	{ id: '57', sc: '58', episode: '1', isComplete: true },
	{ id: '58', sc: '59', episode: '1', isComplete: true },
	{ id: '59', sc: '60', episode: '1', isComplete: true },
	{ id: '60', sc: '61', episode: '1', isComplete: true },
	{ id: '61', sc: '62', episode: '1', isComplete: false },
	{ id: '62', sc: '63', episode: '1', isComplete: false },
	{ id: '63', sc: '64', episode: '1', isComplete: false },
	{ id: '64', sc: '65', episode: '1', isComplete: false },
	{ id: '65', sc: '66', episode: '1', isComplete: false },
	{ id: '66', sc: '67', episode: '1', isComplete: true },
	{ id: '67', sc: '68', episode: '1', isComplete: true },
	{ id: '68', sc: '69', episode: '1', isComplete: true },
	{ id: '69', sc: '70', episode: '1', isComplete: true },
	{ id: '70', sc: '71', episode: '1', isComplete: false },
	{ id: '71', sc: '72', episode: '1', isComplete: false },
	{ id: '72', sc: '73', episode: '1', isComplete: true },
	{ id: '73', sc: '74', episode: '1', isComplete: false },
	{ id: '74', sc: '75', episode: '1', isComplete: true },
	{ id: '75', sc: '1', episode: '2', isComplete: false },
	{ id: '76', sc: '2', episode: '2', isComplete: false },
	{ id: '77', sc: '3', episode: '2', isComplete: false },
	{ id: '78', sc: '4', episode: '2', isComplete: false },
	{ id: '79', sc: '5', episode: '2', isComplete: true },
	{ id: '80', sc: '6', episode: '2', isComplete: false },
	{ id: '81', sc: '7', episode: '2', isComplete: true },
	{ id: '82', sc: '8', episode: '2', isComplete: true },
	{ id: '83', sc: '9', episode: '2', isComplete: true },
	{ id: '84', sc: '10', episode: '2', isComplete: true },
	{ id: '85', sc: '11', episode: '2', isComplete: false },
	{ id: '86', sc: '12', episode: '2', isComplete: true },
	{ id: '87', sc: '13', episode: '2', isComplete: true },
	{ id: '88', sc: '14', episode: '2', isComplete: true },
	{ id: '89', sc: '15', episode: '2', isComplete: true },
	{ id: '90', sc: '16', episode: '2', isComplete: true },
	{ id: '91', sc: '17', episode: '2', isComplete: false },
	{ id: '92', sc: '18', episode: '2', isComplete: false },
	{ id: '93', sc: '19', episode: '2', isComplete: false },
	{ id: '94', sc: '20', episode: '2', isComplete: false },
	{ id: '95', sc: '21', episode: '2', isComplete: true },
	{ id: '96', sc: '22', episode: '2', isComplete: false },
	{ id: '97', sc: '23', episode: '2', isComplete: false },
	{ id: '98', sc: '24', episode: '2', isComplete: true },
	{ id: '99', sc: '25', episode: '2', isComplete: true },
	{ id: '100', sc: '26', episode: '2', isComplete: false },
	{ id: '101', sc: '27', episode: '2', isComplete: true },
	{ id: '102', sc: '28', episode: '2', isComplete: true },
	{ id: '103', sc: '29', episode: '2', isComplete: false },
	{ id: '104', sc: '30', episode: '2', isComplete: true },
	{ id: '105', sc: '31', episode: '2', isComplete: false },
	{ id: '117', sc: '32', episode: '2', isComplete: false },
	{ id: '118', sc: '33', episode: '2', isComplete: true },
	{ id: '119', sc: '34', episode: '2', isComplete: false },
	{ id: '120', sc: '35', episode: '2', isComplete: true },
	{ id: '121', sc: '36', episode: '2', isComplete: false },
	{ id: '122', sc: '37', episode: '2', isComplete: false },
	{ id: '123', sc: '38', episode: '2', isComplete: true },
	{ id: '124', sc: '39', episode: '2', isComplete: true },
	{ id: '125', sc: '40', episode: '2', isComplete: false },
	{ id: '126', sc: '41', episode: '2', isComplete: true },
	{ id: '127', sc: '42', episode: '2', isComplete: false },
	{ id: '128', sc: '43', episode: '2', isComplete: true },
	{ id: '129', sc: '44', episode: '2', isComplete: false },
	{ id: '130', sc: '45', episode: '2', isComplete: true },
	{ id: '131', sc: '46', episode: '2', isComplete: true },
	{ id: '132', sc: '47', episode: '2', isComplete: false },
	{ id: '133', sc: '48', episode: '2', isComplete: true },
	{ id: '134', sc: '49', episode: '2', isComplete: true },
	{ id: '135', sc: '50', episode: '2', isComplete: true },
	{ id: '136', sc: '51', episode: '2', isComplete: false },
	{ id: '137', sc: '52', episode: '2', isComplete: true },
	{ id: '138', sc: '53', episode: '2', isComplete: false },
	{ id: '139', sc: '54', episode: '2', isComplete: true },
	{ id: '140', sc: '55', episode: '2', isComplete: true },
	{ id: '141', sc: '56', episode: '2', isComplete: false },
	{ id: '142', sc: '57', episode: '2', isComplete: true },
	{ id: '143', sc: '58', episode: '2', isComplete: false },
	{ id: '144', sc: '59', episode: '2', isComplete: true },
	{ id: '145', sc: '60', episode: '2', isComplete: true },
	{ id: '146', sc: '61', episode: '2', isComplete: false },
	{ id: '147', sc: '62', episode: '2', isComplete: true },
	{ id: '148', sc: '63', episode: '2', isComplete: true },
	{ id: '149', sc: '64', episode: '2', isComplete: true },
	{ id: '150', sc: '65', episode: '2', isComplete: false },
	{ id: '151', sc: '66', episode: '2', isComplete: true },
	{ id: '152', sc: '67', episode: '2', isComplete: false },
	{ id: '153', sc: '68', episode: '2', isComplete: false },
	{ id: '154', sc: '69', episode: '2', isComplete: true },
	{ id: '155', sc: '70', episode: '2', isComplete: false },
	{ id: '156', sc: '71', episode: '2', isComplete: false },
	{ id: '157', sc: '72', episode: '2', isComplete: true },
	{ id: '158', sc: '73', episode: '2', isComplete: false },
	{ id: '159', sc: '74', episode: '2', isComplete: true },
	{ id: '160', sc: '75', episode: '2', isComplete: false }
]

export function ProgressReportWaffleOverviewListItem({ id }: Props): JSX.Element {
  const breakdown = breakdowns.find(b => b.id === id)
  return (
		<>
			{breakdown &&
				<ProgressReportWaffleOverviewChip isComplete={breakdown?.isComplete} episode={breakdown?.episode}>
					{breakdown?.sc}
				</ProgressReportWaffleOverviewChip>
			}
		</>
  )
}